fix pipelines to show erros

diff --git a/.github/actions/deploy-docker-compose/action.yml b/.github/actions/deploy-docker-compose/action.yml
--- a/.github/actions/deploy-docker-compose/action.yml
+++ b/.github/actions/deploy-docker-compose/action.yml
@@ -57,3 +57,24 @@ runs:
           cd ${{ inputs.service_name }}
           docker-compose down
           docker-compose up -d 
+
+    - name: Check That Services Are Running
+      uses: appleboy/ssh-action@master
+      with:
+        host: ${{ inputs.server_host }}
+        username: ${{ inputs.server_username }}
+        port: ${{ inputs.server_port }}
+        key: ${{ inputs.server_ssh_key }}
+        script: |
+          cd ${{ inputs.service_name }}
+          
+          STATUS_OUTPUT=$(docker-compose ps --format '{{.Name}}\t{{.Status}}')
+          FAILED_SERVICES=$(echo "$STATUS_OUTPUT" | grep -v "Up " | grep -v "^$" || true)
+          
+          if [ -n "$FAILED_SERVICES" ]; then
+            echo "❌ The following services are not running properly:"
+            echo "$FAILED_SERVICES"
+            exit 1
+          else
+            echo "✅ All services are running successfully"
+          fi
